import AnimationWrapper from '@components/AnimationWrapper';
import WhyChooseClyde from '@components/WhyChooseClyde';
import ContactSection from '@components/contact/ContactSection';
import Image from 'next/image';
export const metadata = {
  title: 'Cl',
  description: 'Generated by create next app',
};
export default function ContactPage() {
  return (
    <AnimationWrapper>
      <div className="inner-container-2">
        <div className="page-break"></div>
        <div className="flex items-center text-center flex-col">
          <Image src="/images/success.png" width={200} height={200} />
          <h1 className="section-heading mt-8">Thank you </h1>
          <p className="section-subheading">
            We have received your message, one of our team will be in contact
            shortly.
          </p>
        </div>
        <div className="page-break hidden md:block"></div>
      </div>
    </AnimationWrapper>
  );
}
