import '@styles/globals.css';
import '@styles/custom-swiper-styles.css';
import '@styles/fontello/css/fontello.css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css';
import Nav from '@components/nav/Nav';
import Footer from '@components/Footer';
import CookieConsentManager from '@components/CookieConsentManager';
export const metadata = {
  title: 'Clyde Ventures | Salesforce | Consultancy | MBA | Fireproof Panels',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="app flex flex-col justify-between h-[100vh] max-w-[100vw]">
        <CookieConsentManager />
        <div>
          <Nav />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
